apiVersion: v1
kind: Service
metadata:
  name: new
  labels:
    app: new
    service: new
spec:
  selector:
    app: new
    service: new
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP